#----------------------------------------------------------------------------
#       Make Workspace
#
# 
#
# This file was generated by MPC.  Any changes made directly to
# this file will be lost the next time it is generated.
#
# MPC Command:
# /home/alistenberger/MPC/MPC/mwc.pl -type make
#
#----------------------------------------------------------------------------


all: Sorting

depend: Sorting-depend

clean generated realclean check-syntax $(CUSTOM_TARGETS):
	@$(MAKE) -f Makefile.Sorting $(@)

.PHONY: Sorting
Sorting:
	@$(MAKE) -f Makefile.Sorting all

.PHONY: Sorting-depend
Sorting-depend:
	@$(MAKE) -f Makefile.Sorting depend

project_name_list:
	@echo Sorting
